import {StyleSheet} from 'react-native';
import AppTheme from './AppTheme';

const {colors} = AppTheme;

const TextStyles = StyleSheet.create({
  headlineWhiteRight: {
    fontFamily: 'Avenir',
    fontSize: 40,
    fontWeight: '900',
    fontStyle: 'normal',
    lineHeight: 48,
    letterSpacing: 0.41,
    textAlign: 'right',
    color: colors.colorsBasicLight,
  },
  headlineWhiteLeft: {
    fontFamily: 'Avenir',
    fontSize: 40,
    fontWeight: '900',
    fontStyle: 'normal',
    lineHeight: 48,
    letterSpacing: 0.41,
    color: colors.colorsBasicLight,
  },
  headlineWhiteCenter: {
    fontFamily: 'Avenir',
    fontSize: 40,
    fontWeight: '900',
    fontStyle: 'normal',
    lineHeight: 48,
    letterSpacing: 0.41,
    textAlign: 'center',
    color: colors.colorsBasicLight,
  },
  headlineDarkRight: {
    fontFamily: 'Avenir',
    fontSize: 40,
    fontWeight: '900',
    fontStyle: 'normal',
    lineHeight: 48,
    letterSpacing: 0.41,
    textAlign: 'right',
    color: colors.colorsBasicDark,
  },
  headlineDarkCenter: {
    fontFamily: 'Avenir',
    fontSize: 40,
    fontWeight: '900',
    fontStyle: 'normal',
    lineHeight: 48,
    letterSpacing: 0.41,
    textAlign: 'center',
    color: colors.colorsBasicDark,
  },
  headlineBrandRight: {
    fontFamily: 'Avenir',
    fontSize: 40,
    fontWeight: '900',
    fontStyle: 'normal',
    lineHeight: 48,
    letterSpacing: 0.41,
    textAlign: 'right',
    color: colors.colorsAccentMainColor,
  },
  headlineBrandLeft: {
    fontFamily: 'Avenir',
    fontSize: 40,
    fontWeight: '900',
    fontStyle: 'normal',
    lineHeight: 48,
    letterSpacing: 0.41,
    color: colors.colorsAccentMainColor,
  },
  headlineBrandCenter: {
    fontFamily: 'Avenir',
    fontSize: 40,
    fontWeight: '900',
    fontStyle: 'normal',
    lineHeight: 48,
    letterSpacing: 0.41,
    textAlign: 'center',
    color: colors.colorsAccentMainColor,
  },
  headlineDarkLeft: {
    fontFamily: 'SFProText',
    fontSize: 40,
    fontWeight: '600',
    fontStyle: 'normal',
    lineHeight: 48,
    letterSpacing: 0.41,
    color: colors.colorsBasicDark,
  },
  largeTitleWhiteRegular: {
    fontFamily: 'SFProText',
    fontSize: 34,
    fontWeight: 'bold',
    fontStyle: 'normal',
    lineHeight: 41,
    letterSpacing: 0.41,
    color: colors.colorsBasicLight,
  },
  largeTitleDarkRegular: {
    fontFamily: 'SFProText',
    fontSize: 34,
    fontWeight: 'bold',
    fontStyle: 'normal',
    lineHeight: 41,
    letterSpacing: 0.41,
    color: '#333333',
  },
  title1WhiteBoldRight: {
    fontFamily: 'SFProText',
    fontSize: 28,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.45,
    textAlign: 'right',
    color: colors.colorsBasicLight,
  },
  title1WhiteBoldLeft: {
    fontFamily: 'SFProText',
    fontSize: 28,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.45,
    color: colors.colorsBasicLight,
  },
  title1WhiteBoldCenter: {
    fontFamily: 'SFProText',
    fontSize: 28,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.45,
    textAlign: 'center',
    color: colors.colorsBasicLight,
  },
  title1GreyBoldRight: {
    fontFamily: 'SFProText',
    fontSize: 28,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.45,
    textAlign: 'right',
    color: colors.scrimsDarker60,
  },
  title1GreyBoldLeft: {
    fontFamily: 'SFProText',
    fontSize: 28,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.45,
    color: colors.scrimsDarker60,
  },
  title1GreyBoldCenter: {
    fontFamily: 'SFProText',
    fontSize: 28,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.45,
    textAlign: 'center',
    color: colors.scrimsDarker60,
  },
  title1DarkBoldRight: {
    fontFamily: 'SFProText',
    fontSize: 28,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.45,
    textAlign: 'right',
    color: '#333333',
  },
  title1DarkBoldLeft: {
    fontFamily: 'SFProText',
    fontSize: 28,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.45,
    color: '#333333',
  },
  title1DarkBoldCenter: {
    fontFamily: 'SFProText',
    fontSize: 28,
    fontWeight: '600',
    fontStyle: 'normal',
    lineHeight: 20,
    letterSpacing: -0.45,
    textAlign: 'center',
    color: '#333333',
  },
  title1BrandBoldRight: {
    fontFamily: 'SFProText',
    fontSize: 28,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.45,
    textAlign: 'right',
    color: colors.colorsAccentMainColor,
  },
  title1BrandBoldLeft: {
    fontFamily: 'SFProText',
    fontSize: 28,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.45,
    color: colors.colorsAccentMainColor,
  },
  title1BrandBoldCenter: {
    fontFamily: 'SFProText',
    fontSize: 28,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.45,
    textAlign: 'center',
    color: colors.colorsAccentMainColor,
  },
  title1WhiteRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 28,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.45,
    textAlign: 'right',
    color: colors.colorsBasicLight,
  },
  title1WhiteRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 28,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.45,
    color: colors.colorsBasicLight,
  },
  title1WhiteRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 28,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.45,
    textAlign: 'center',
    color: colors.colorsBasicLight,
  },
  title1GreyRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 28,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.45,
    textAlign: 'right',
    color: colors.scrimsDarker60,
  },
  title1GreyRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 28,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.45,
    color: colors.scrimsDarker60,
  },
  title1GreyRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 28,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.45,
    textAlign: 'center',
    color: colors.scrimsDarker60,
  },
  title1DarkRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 28,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.45,
    textAlign: 'right',
    color: '#333333',
  },
  title1DarkRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 28,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.45,
    color: '#333333',
  },
  title1DarkRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 28,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.45,
    textAlign: 'center',
    color: '#333333',
  },
  title1BrandRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 28,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.45,
    textAlign: 'right',
    color: colors.colorsAccentMainColor,
  },
  title1BrandRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 28,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.45,
    color: colors.colorsAccentMainColor,
  },
  title1BrandRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 28,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.45,
    textAlign: 'center',
    color: colors.colorsAccentMainColor,
  },
  title2DarkBoldLeft: {
    fontFamily: 'SFProText',
    fontSize: 22,
    fontWeight: 'bold',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: '#333333',
  },
  title2WhiteBoldRight: {
    fontFamily: 'SFProText',
    fontSize: 22,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.35,
    textAlign: 'right',
    color: colors.colorsBasicLight,
  },
  title2WhiteBoldLeft: {
    fontFamily: 'SFProText',
    fontSize: 22,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.35,
    color: colors.colorsBasicLight,
  },
  title2WhiteBoldCenter: {
    fontFamily: 'SFProText',
    fontSize: 22,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.35,
    textAlign: 'center',
    color: colors.colorsBasicLight,
  },
  title2GreyBoldRight: {
    fontFamily: 'SFProText',
    fontSize: 22,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.35,
    textAlign: 'right',
    color: colors.scrimsDarker60,
  },
  title2GreyBoldLeft: {
    fontFamily: 'SFProText',
    fontSize: 22,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.35,
    color: colors.scrimsDarker60,
  },
  title2GreyBoldCenter: {
    fontFamily: 'SFProText',
    fontSize: 22,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.35,
    textAlign: 'center',
    color: colors.scrimsDarker60,
  },
  title2DarkBoldRight: {
    fontFamily: 'SFProText',
    fontSize: 22,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.35,
    textAlign: 'right',
    color: '#333333',
  },
  title2DarkBoldCenter: {
    fontFamily: 'SFProText',
    fontSize: 22,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.35,
    textAlign: 'center',
    color: '#333333',
  },
  title2BrandBoldRight: {
    fontFamily: 'SFProText',
    fontSize: 22,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.35,
    textAlign: 'right',
    color: colors.colorsAccentMainColor,
  },
  title2BrandBoldLeft: {
    fontFamily: 'SFProText',
    fontSize: 22,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.35,
    color: colors.colorsAccentMainColor,
  },
  title2BrandBoldCenter: {
    fontFamily: 'SFProText',
    fontSize: 22,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.35,
    textAlign: 'center',
    color: colors.colorsAccentMainColor,
  },
  title2WhiteRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 22,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.35,
    textAlign: 'right',
    color: colors.colorsBasicLight,
  },
  title2WhiteRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 22,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.35,
    color: colors.colorsBasicLight,
  },
  title2WhiteRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 22,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.35,
    textAlign: 'center',
    color: colors.colorsBasicLight,
  },
  title2GreyRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 22,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.35,
    textAlign: 'right',
    color: colors.scrimsDarker60,
  },
  title2GreyRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 22,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.35,
    color: colors.scrimsDarker60,
  },
  title2GreyRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 22,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.35,
    textAlign: 'center',
    color: colors.scrimsDarker60,
  },
  title2DarkRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 22,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.35,
    textAlign: 'right',
    color: '#333333',
  },
  title2DarkRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 22,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.35,
    color: '#333333',
  },
  title2DarkRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 22,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.35,
    textAlign: 'center',
    color: '#333333',
  },
  title2BrandRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 22,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.35,
    textAlign: 'right',
    color: colors.colorsAccentMainColor,
  },
  title2BrandRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 22,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.35,
    color: colors.colorsAccentMainColor,
  },
  title2BrandRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 22,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.35,
    textAlign: 'center',
    color: colors.colorsAccentMainColor,
  },
  title3WhiteBoldRight: {
    fontFamily: 'SFProText',
    fontSize: 20,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.32,
    textAlign: 'right',
    color: colors.colorsBasicLight,
  },
  title3WhiteBoldLeft: {
    fontFamily: 'SFProText',
    fontSize: 20,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.32,
    color: colors.colorsBasicLight,
  },
  title3WhiteBoldCenter: {
    fontFamily: 'SFProText',
    fontSize: 20,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.32,
    textAlign: 'center',
    color: colors.colorsBasicLight,
  },
  title3GreyBoldRight: {
    fontFamily: 'SFProText',
    fontSize: 20,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.32,
    textAlign: 'right',
    color: colors.scrimsDarker60,
  },
  title3GreyBoldLeft: {
    fontFamily: 'SFProText',
    fontSize: 20,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.32,
    color: colors.scrimsDarker60,
  },
  title3GreyBoldCenter: {
    fontFamily: 'SFProText',
    fontSize: 20,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.32,
    textAlign: 'center',
    color: colors.scrimsDarker60,
  },
  title3DarkBoldRight: {
    fontFamily: 'SFProText',
    fontSize: 20,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.32,
    textAlign: 'right',
    color: '#333333',
  },
  title3DarkBoldLeft: {
    fontFamily: 'SFProText',
    fontSize: 20,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.32,
    color: '#333333',
  },
  title3DarkBoldCenter: {
    fontFamily: 'SFProText',
    fontSize: 20,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.32,
    textAlign: 'center',
    color: '#333333',
  },
  title3BrandBoldRight: {
    fontFamily: 'SFProText',
    fontSize: 20,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.32,
    textAlign: 'right',
    color: colors.colorsAccentMainColor,
  },
  title3BrandBoldLeft: {
    fontFamily: 'SFProText',
    fontSize: 20,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.32,
    color: colors.colorsAccentMainColor,
  },
  title3BrandBoldCenter: {
    fontFamily: 'SFProText',
    fontSize: 20,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.32,
    textAlign: 'center',
    color: colors.colorsAccentMainColor,
  },
  title3WhiteRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 20,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.32,
    textAlign: 'right',
    color: colors.colorsBasicLight,
  },
  title3WhiteRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 20,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.32,
    color: colors.colorsBasicLight,
  },
  title3WhiteRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 20,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.32,
    textAlign: 'center',
    color: colors.colorsBasicLight,
  },
  title3GreyRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 20,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.32,
    textAlign: 'right',
    color: colors.scrimsDarker60,
  },
  title3GreyRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 20,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.32,
    color: colors.scrimsDarker60,
  },
  title3GreyRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 20,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.32,
    textAlign: 'center',
    color: colors.scrimsDarker60,
  },
  title3DarkRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 20,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.32,
    textAlign: 'right',
    color: '#333333',
  },
  title3DarkRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 20,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.32,
    color: '#333333',
  },
  title3DarkRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 20,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.32,
    textAlign: 'center',
    color: '#333333',
  },
  title3BrandRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 20,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.32,
    textAlign: 'right',
    color: colors.colorsAccentMainColor,
  },
  title3BrandRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 20,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.32,
    color: colors.colorsAccentMainColor,
  },
  title3BrandRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 20,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.32,
    textAlign: 'center',
    color: colors.colorsAccentMainColor,
  },
  subheadWhiteBoldRight: {
    fontFamily: 'SFProText',
    fontSize: 17,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.27,
    textAlign: 'right',
    color: colors.colorsBasicLight,
  },
  subheadWhiteBoldLeft: {
    fontFamily: 'SFProText',
    fontSize: 17,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.27,
    color: colors.colorsBasicLight,
  },
  subheadWhiteBoldCenter: {
    fontFamily: 'SFProText',
    fontSize: 17,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.27,
    textAlign: 'center',
    color: colors.colorsBasicLight,
  },
  subheadGreyBoldRight: {
    fontFamily: 'SFProText',
    fontSize: 17,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.27,
    textAlign: 'right',
    color: colors.scrimsDarker60,
  },
  subheadGreyBoldLeft: {
    fontFamily: 'SFProText',
    fontSize: 17,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.27,
    color: colors.scrimsDarker60,
  },
  subheadGreyBoldCenter: {
    fontFamily: 'SFProText',
    fontSize: 17,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.27,
    textAlign: 'center',
    color: colors.scrimsDarker60,
  },
  subheadDarkBoldRight: {
    fontFamily: 'SFProText',
    fontSize: 17,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.27,
    textAlign: 'right',
    color: '#333333',
  },
  subheadDarkBoldLeft: {
    fontFamily: 'SFProText',
    fontSize: 17,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.27,
    color: '#333333',
  },
  subheadDarkBoldCenter: {
    fontFamily: 'SFProText',
    fontSize: 17,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.27,
    textAlign: 'center',
    color: '#333333',
  },
  subheadBrandBoldRight: {
    fontFamily: 'SFProText',
    fontSize: 17,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.27,
    textAlign: 'right',
    color: colors.colorsAccentMainColor,
  },
  subheadBrandBoldLeft: {
    fontFamily: 'SFProText',
    fontSize: 17,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.27,
    color: colors.colorsAccentMainColor,
  },
  subheadBrandBoldCenter: {
    fontFamily: 'SFProText',
    fontSize: 17,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.27,
    textAlign: 'center',
    color: colors.colorsAccentMainColor,
  },
  bodyWhiteRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 17,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.27,
    textAlign: 'right',
    color: colors.colorsBasicLight,
  },
  bodyWhiteRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 17,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.27,
    color: colors.colorsBasicLight,
  },
  bodyWhiteRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 17,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.27,
    textAlign: 'center',
    color: colors.colorsBasicLight,
  },
  bodyGreyRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 17,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.27,
    textAlign: 'right',
    color: colors.scrimsDarker60,
  },
  bodyGreyRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 17,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.27,
    color: colors.scrimsDarker60,
  },
  bodyGreyRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 17,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.27,
    textAlign: 'center',
    color: colors.scrimsDarker60,
  },
  bodyDarkRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 17,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.27,
    textAlign: 'right',
    color: '#333333',
  },
  bodyDarkRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 17,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: '#333333',
  },
  bodyDarkRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 17,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.27,
    textAlign: 'center',
    color: '#333333',
  },
  bodyBrandRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 17,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.27,
    textAlign: 'right',
    color: colors.colorsAccentMainColor,
  },
  bodyBrandRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 17,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.27,
    color: colors.colorsAccentMainColor,
  },
  bodyBrandRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 17,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.27,
    textAlign: 'center',
    color: colors.colorsAccentMainColor,
  },
  calloutWhiteRight: {
    fontFamily: 'SFProText',
    fontSize: 16,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.26,
    textAlign: 'right',
    color: colors.colorsBasicLight,
  },
  calloutWhiteLeft: {
    fontFamily: 'SFProText',
    fontSize: 16,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.26,
    color: colors.colorsBasicLight,
  },
  calloutWhiteCenter: {
    fontFamily: 'SFProText',
    fontSize: 16,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.26,
    textAlign: 'center',
    color: colors.colorsBasicLight,
  },
  calloutSecRight: {
    fontFamily: 'SFProText',
    fontSize: 16,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.26,
    textAlign: 'right',
    color: colors.colorsAccentSecandry,
  },
  calloutSecLeft: {
    fontFamily: 'SFProText',
    fontSize: 16,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.26,
    color: colors.colorsAccentSecandry,
  },
  calloutSecCenter: {
    fontFamily: 'SFProText',
    fontSize: 16,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.26,
    textAlign: 'center',
    color: colors.colorsAccentSecandry,
  },
  calloutGreyRight: {
    fontFamily: 'SFProText',
    fontSize: 16,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.26,
    textAlign: 'right',
    color: colors.scrimsDarker60,
  },
  calloutGreyLeft: {
    fontFamily: 'SFProText',
    fontSize: 16,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.26,
    color: colors.scrimsDarker60,
  },
  calloutGreyCenter: {
    fontFamily: 'SFProText',
    fontSize: 16,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.26,
    textAlign: 'center',
    color: colors.scrimsDarker60,
  },
  calloutDarkRight: {
    fontFamily: 'SFProText',
    fontSize: 16,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.26,
    textAlign: 'right',
    color: '#333333',
  },
  calloutDarkRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 16,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.26,
    textAlign: 'center',
    color: colors.colorsBasicDark,
  },
  calloutDarkLeft: {
    fontFamily: 'SFProText',
    fontSize: 16,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.26,
    color: '#333333',
  },
  calloutDarkCenter: {
    fontFamily: 'SFProText',
    fontSize: 16,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.26,
    textAlign: 'center',
    color: '#333333',
  },
  calloutBrandRight: {
    fontFamily: 'SFProText',
    fontSize: 16,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.26,
    textAlign: 'right',
    color: colors.colorsAccentMainColor,
  },
  calloutBrandLeft: {
    fontFamily: 'SFProText',
    fontSize: 16,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.26,
    color: colors.colorsAccentMainColor,
  },
  calloutBrandCenter: {
    fontFamily: 'SFProText',
    fontSize: 16,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: -0.26,
    textAlign: 'center',
    color: colors.colorsAccentMainColor,
  },
  body2WhiteRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 15,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.24,
    textAlign: 'right',
    color: colors.colorsBasicLight,
  },
  body2WhiteRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 15,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.24,
    color: colors.colorsBasicLight,
  },
  body2WhiteRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 15,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.24,
    textAlign: 'center',
    color: colors.colorsBasicLight,
  },
  body2GreyRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 15,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.24,
    textAlign: 'right',
    color: colors.scrimsDarker60,
  },
  body2GreyRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 15,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.24,
    color: colors.scrimsDarker60,
  },
  body2GreyRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 15,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.24,
    textAlign: 'center',
    color: colors.scrimsDarker60,
  },
  body2DarkRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 15,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.24,
    textAlign: 'right',
    color: '#333333',
  },
  body2DarkRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 15,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.24,
    color: '#333333',
  },
  body2DarkRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 15,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.24,
    textAlign: 'center',
    color: '#333333',
  },
  body2BrandRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 15,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.24,
    textAlign: 'right',
    color: colors.colorsAccentMainColor,
  },
  body2BrandRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 15,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.24,
    color: colors.colorsAccentMainColor,
  },
  body2BrandRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 15,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.24,
    textAlign: 'center',
    color: colors.colorsAccentMainColor,
  },
  footnoteDarkRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 13,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.21,
    color: '#333333',
  },
  footnoteDarkRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 13,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.21,
    textAlign: 'center',
    color: '#333333',
  },
  footnoteWhiteRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 13,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.21,
    textAlign: 'right',
    color: colors.colorsBasicLight,
  },
  footnoteWhiteRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 13,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.21,
    color: colors.colorsBasicLight,
  },
  footnoteWhiteRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 13,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.21,
    textAlign: 'center',
    color: colors.colorsBasicLight,
  },
  footnoteGreyRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 13,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.21,
    textAlign: 'right',
    color: colors.scrimsDarker60,
  },
  footnoteGreyRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 13,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.21,
    color: colors.scrimsDarker60,
  },
  footnoteGreyRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 13,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.21,
    textAlign: 'center',
    color: colors.scrimsDarker60,
  },
  footnoteDarkRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 13,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.21,
    textAlign: 'right',
    color: '#333333',
  },
  footnoteBrandRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 13,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.21,
    textAlign: 'right',
    color: colors.colorsAccentMainColor,
  },
  footnoteBrandRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 13,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.21,
    color: colors.colorsAccentMainColor,
  },
  footnoteBrandRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 13,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.21,
    textAlign: 'center',
    color: colors.colorsAccentMainColor,
  },
  caption1WhiteRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.19,
    textAlign: 'right',
    color: colors.colorsBasicLight,
  },
  caption1WhiteRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.19,
    color: colors.colorsBasicLight,
  },
  caption1WhiteRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.19,
    textAlign: 'center',
    color: colors.colorsBasicLight,
  },
  caption1GreyRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.19,
    textAlign: 'right',
    color: colors.scrimsDarker60,
  },
  caption1GreyRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.19,
    color: colors.scrimsDarker60,
  },
  caption1GreyRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.19,
    textAlign: 'center',
    color: colors.scrimsDarker60,
  },
  caption1DarkRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.19,
    textAlign: 'right',
    color: '#333333',
  },
  caption1DarkRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.19,
    color: '#333333',
  },
  caption1DarkRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.19,
    textAlign: 'center',
    color: '#333333',
  },
  caption1BrandRegularRight: {
    fontFamily: 'SFProText',
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.19,
    textAlign: 'right',
    color: colors.colorsAccentMainColor,
  },
  caption1BrandRegularLeft: {
    fontFamily: 'SFProText',
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.19,
    color: colors.colorsAccentMainColor,
  },
  caption1BrandRegularCenter: {
    fontFamily: 'SFProText',
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.19,
    textAlign: 'center',
    color: colors.colorsAccentMainColor,
  },
});
