const Routes = {
  Login: 'Login',
  Signup: 'Create Account',
  ForgetPassword: 'Reset Password',
  Onboarding: 'Onboarding',
  Splash: 'Splash',
  Home: 'Home',
  Explore: 'Explore',
  Rooms: 'Rooms',
  Dining: 'Dining',
  Paynow: 'Pay Now',
  loyalty_card: 'Loyalty Card',
  dinning_offers: 'Dining Offers',
  Wellness: 'Wellness',
  Banquets: 'Banquets',
  Cattering: 'Catering',
  Corporate: 'Corporate',
  Offers: 'Offers',
  Packages: 'Packages',
  PackageDetail: 'PackageDetail',
  Blogs: 'Blogs',
  LoyaltyCard: 'Loyalty Card',
  MyBookings: 'My Bookings',
  Upcoming: 'Upcoming',
  History: 'History',
  Rewards: 'Rewards',
  Profile: 'ProfileScreen',
  Contact: 'Contact',
  Notifications: 'Notification',
  DiningDetails: 'DiningDetails',
  RoomDetail: 'RoomDetail',
  SelectRooms: 'Select Rooms',
  GuestDetails: 'Guest Details',
  PaymentDetails: 'Payment Details',
  Country: 'Country',
  LoginScreen: 'LoginScreen',
  // MyBookings: 'MyBookingsScreen',
  EditProfile: 'Edit Profile',
  CancellationPolicy: 'Cancellation Policy',
  cancelBooking: 'Cancel Booking',
  ChangePassword: 'Change Password',
  NotificationSetting: 'Notifications',
  WebViewScreen: 'WebviewScreen',
  BookingCompletedScreen: 'BookingCompletedScreen',
};
export default Routes;
