require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

pod 'Firebase', :modular_headers => true
pod 'FirebaseCoreInternal', :modular_headers => true
pod 'FirebaseCore', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true
pod 'OpenSSL-Universal', '~>1.1.180'
target 'reactNativeReduxBoilerplate' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'reactNativeReduxBoilerplateTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  
end
target 'reactNativeReduxBoilerplate-tvOS' do
  # Pods for reactNativeReduxBoilerplate-tvOS

  target 'reactNativeReduxBoilerplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
    end
  end
end