const CHANGE_BRANCH = 'CHANGE_BRANCH';
const BOOK_ROOM = 'BOOK_ROOM';
const GET_COUNTRIES = 'GET_COUNTRIES';
const GET_ROOMS = 'GET_ROOMS';
const GET_AVAILABLE_ROOMS = 'GET_AVAILABLE_ROOMS';
const GET_AVAILABLE_ROOM = 'GET_AVAILABLE_ROOM';
const GET_ALL_ROOMS = 'GET_ALL_ROOMS';
const GET_ALL_PACKAGES = 'GET_ALL_PACKAGES';
const GET_PACKAGE_DETAILS = 'GET_PACKAGE_DETAILS';
const GET_AVAILABLE_PACKAGE = 'GET_AVAILABLE_PACKAGE';
const GET_ADD_ON = 'GET_ADD_ON';
const GET_BOOKINGS = 'GET_BOOKINGS';
const LOGIN = 'LOGIN';
const SIGNUP = 'SIGNUP';
const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
const UPDATE_PROFILE = 'UPDATE_PROFILE';
const IS_LOGGED_IN = 'IS_LOGGED_IN';
const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
const OPEN_SHEET = 'OPEN_SHEET';
// const SELECTED_CURRENCY = 'SELECTED_CURRENCY';
export {
  CHANGE_BRANCH,
  BOOK_ROOM,
  GET_ROOMS,
  GET_AVAILABLE_ROOMS,
  GET_AVAILABLE_ROOM,
  // GET_AVAILABLE_PACKAGE,
  GET_PACKAGE_DETAILS,
  GET_ADD_ON,
  GET_BOOKINGS,
  LOGIN,
  SIGNUP,
  FORGOT_PASSWORD,
  CHANGE_PASSWORD,
  UPDATE_PROFILE,
  IS_LOGGED_IN,
  GET_NOTIFICATIONS,
  OPEN_SHEET,
  GET_ALL_ROOMS,
  GET_ALL_PACKAGES,
  // SELECTED_CURRENCY,
};
